name: UNET_IC_SE_CIFAR10
seed: 1234
track: &track True
script_path: /Users/bniepce/Projects/Research/MRI/Spiking-fastMRI/
model:
  class_name: VanillaUNet
  module_name: src.net.models.unet.vanilla
  parameters:
    in_channels: 1
    out_channels: 1
    features: !!python/list [32, 64, 128, 256]
    drob_prob: 0.01
    use_attention: True

dataloader:
  class_name: ReconstructionCIFAR10Loader
  module_name: src.data.loaders.cifar10
  parameters:
    data_dir: ./data
    input_size: !!python/tuple [64, 64]
    batch_size: 128
    num_workers: 8
    debug: False

trainer:
  class_name: FastMRITrainer
  module_name: tasks.cifarRecon.trainer
  parameters:
    num_epochs: 20
    early_stopping_patience: 20
    lr_scheduler: plateau
    lr: 0.0001
    weight_decay: 0.0
    track: *track
    loss:
      module_name: torch.nn
      class_name: L1Loss
      parameters:
    metric:
      module_name: torchmetrics.image
      class_name: PeakSignalNoiseRatio
      parameters:

experiment:
  class_name: BaseExperiment
  module_name: src.core.experiment
